### ISSUE TITLE
[Priest-human] trainer not teaching ranks 4+5 of Feedback

### ISSUE THREAD

**Issue by Cabro** [FeenixServerProject/Old_1.12_Bugtracker#1067]
The trainer teaches you Feeback only ranks 2 and 3 (rank 1 is quest reward). It should also teach ranks 4 and 5 (ids 19274 and 19275).

As you can see from http://www.wowwiki.com/Feedback_%28priest_ability%29 , ranks 1-2-3-4-5 existed in vanilla, and rank 6 in TBC.

Please add those to the trainer.

http://www.wow-one.com/forum/topic/20237-1121issue-1067-priest-trainer-not-teaching-ranks-45-of-feedback/

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**
