### ISSUE TITLE
Shadoweaver / The Undermarket 

### ISSUE THREAD

**Issue by Shana999** [FeenixServerProject/Old_1.12_Bugtracker#1170]
Hello,

There is this quest Shadoweaver you can accept from : Nilith Lokrav
in Searing Gorge .
Nilith Lokrav Location : 41,74 ( cords from searing Gorge ) 

You have to be 230 + tailor or higher to be able to see/accept this quest.
I have tailor 230 / 300, And compleeted the first quest ''Shadoweaver''
When i pressed accept for the follow up quest called ''The Undermarket''
Its said : not eligible.

I talked with The npc again but she dident gave me any quest anymore,
there wasnt any quest in my quest log, so i logged out and back in again...
same story still no quest.
Please help me with this or if you have experianced the same problem tell me,
( So i know its bugged )

If the feenix team needs anymore information i can provide or help assist
Crushing this bug i'll be happy to do so :)

Ps : I beg you to fix this Feenix Team since This quest is very important to me.

Sincerely yours : Shana

Links :

http://www.wowhead.com/quest=3379
-------------------------------------------------------------
http://www.wowwiki.com/Quest:Shadoweaver

http://www.wowwiki.com/Quest:The_Undermarket           <<<-: The bugged one

( SERVER : Al'akir [instant 60] )

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**
