### ISSUE TITLE
[ZONE TEST] Western Plaguelands - Chromatic Mantle of the Dawn

### ISSUE THREAD

**Issue by Cabro** [FeenixServerProject/Old_1.12_Bugtracker#1376]
http://old.wowhead.com/quest=5517
http://old.wowhead.com/quest=5521
http://old.wowhead.com/quest=5524

These quests are repeatable - they shouldn't be.

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**
