### ISSUE TITLE
[NPC][Spell][Quest] - Wrath of the Blue Flight

### ISSUE THREAD

**Issue by Psykosa** [FeenixServerProject/Old_1.12_Bugtracker#2198]
#1390 

"Haleh is not kicking you across the continents: she should use Haleh's Will (id 17168) and you should get ported in Darrowmere Lake in WPL."

I just accepted this quest and I was not kicked across the continents to Darrowmere Lake.

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**
