### ISSUE TITLE
Quest: Verifying the Corruption

### ISSUE THREAD

**Issue by tonyw1** [FeenixServerProject/Old_1.12_Bugtracker#2370]
The quest objective "Explore the craters in Shatter Scar Vale" does not complete. I have ridden around and walked around the entire area, including the part suggested in http://www.wowhead.com/quest=5156

I believe the quest objective can not be completed. 

My username is wiscur

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**
