### ISSUE TITLE
[Feralas]Pristine yeti hide

### ISSUE THREAD

**Issue by verbie** [FeenixServerProject/Old_1.12_Bugtracker#2592]
the quest item that you pick up which starts the quest says that the quest has a lvl req of 40 but I'm lvl 42 and I cant start it.

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**
